# Generated by Django 3.0 on 2019-12-05 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='created_on',
            new_name='created',
        ),
        migrations.AddField(
            model_name='assignment',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
