# Generated by Django 3.0 on 2019-12-05 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20191205_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
